### ISSUE TITLE
Rowspan and Colspan

### ISSUE THREAD

**Issue by FTorrenegraG** [clarketm/TableExport#27]
The problem with several rowspan and colspan, is fix ?

In my case, I have several rowspan and colspan in the same table, and this is fill using AngularJS, and when export, in xlsx, the table not appear in correct way.

(sorry for my english, not is very good)

**Comment by jmbkeyes** [comment]
I  also came across this issue(table with rowspan and colspan), any feedback on it?

**Comment by clarketm** [comment]
This should have been fixed in [v3.2.10](https://github.com/clarketm/TableExport/tree/v3.2.10). Please let me know as soon as possible if this is not the case.

**Comment by jmbkeyes** [comment]
It seems not fixed yet(rowspan didn't work as expected, and I doesn't test colspan), I used the stable version.

**Comment by clarketm** [comment]
I ran your example in a static browser environment and I do see one major bug related to the `rowspan` attribute. I will fix it for the next patch release (see attached image). Thank your help with this issue.

<img width="702" alt="tableexport-rowspan-bug" src="https://cloud.githubusercontent.com/assets/9957358/20957015/3056811a-bc02-11e6-8cc9-9424a20511a1.png">

`现金` and `1980` should be in column `G` and `H`, respectively.

**Comment by clarketm** [comment]
The new patch will likely come towards the tail-end of the week. I have a solution in the pipeline that warrants more testing before finalization/release.

**Comment by clarketm** [comment]
I am keeping this ticket open in case the fix @ [d6ca877](https://github.com/clarketm/TableExport/commit/d6ca877eb956efb5980fcf116a12baeb9beaa4dd) is not the only issue.

**Comment by basawyer** [comment]
FYI, we are still having this issue as of v3.3.9. We are happy to provide more information, not sure what would be useful. Thanks.

**Comment by basawyer** [comment]
We spent some more time today looking at this issue in hopes of putting together some sort of pull request.

Here's some example DOM structure that we are having issues with:

<table class="pvtTable">
   <thead>
      <tr>
         <th colspan="2" rowspan="1"></th>
         <th>Title</th>
         <th colspan="1" rowspan="2">TitleOne</th>
         <th rowspan="2">Totals</th>
      </tr>
      <tr>
         <th>Title</th>
         <th>Classification</th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <th rowspan="2">TitleOne</th>
         <th rowspan="1" colspan="2">ClassOne</th>
         <td>1</td>
         <td>1</td>
      </tr>
      <tr>
         <th rowspan="1" colspan="2">ClassTwo</th>
         <td>1</td>
         <td>1</td>
      </tr>
      <tr>
         <th colspan="3">Totals</th>
         <td>2</td>
         <td>2</td>
      </tr>
   </tbody>
</table>

It seems there are issues when building the 'rcMap' object. When encountering a rowspan, you account for the next row's column offset in the rcMap object:

```
if (val.hasAttribute('rowspan')) {
    for (var i = 1; i < val.getAttribute('rowspan'); i++) {
        rcMap[ir + i] = rcMap[ir + i] || {};
        rcMap[ir + i][ic] = 1
    }
}
```

But when calculating that next row, the first column might have a colspan, which has already been accounted for during the previous row calculations.  We added some checking for this case and added the offset to the next column:

```
if (val.hasAttribute('colspan')) {
    rcMap[ir] = rcMap[ir] || {};
    if (!rcMap[ir][ic]) {
      rcMap[ir][ic + 1] = val.getAttribute('colspan') - 1
    } else {
      rcMap[ir][ic + 2] = val.getAttribute('colspan') - 1
    }
}
```

Which fixes our export from looking like this:

![screen shot 2017-01-27 at 3 40 29 pm](https://cloud.githubusercontent.com/assets/1329351/22386858/fa425554-e4a6-11e6-9474-6775373adf59.png)

To looking more correct:

![screen shot 2017-01-27 at 3 38 30 pm](https://cloud.githubusercontent.com/assets/1329351/22386800/b78baf44-e4a6-11e6-886f-08c3f93354c0.png)

We are hoping to get a better understanding of how you are using the rcMap object, so we can move to a more generic solution. This patch does not work if we were to add another dimension to our data.

**Comment by nopace** [comment]
![image](https://cloud.githubusercontent.com/assets/13740162/23539986/8250270e-0019-11e7-9091-94be2ecc4768.png)   If you can merge the cell just fine

**Comment by clarketm** [comment]
@basawyer & @nopace – I would really like to get this patched and integrated into [v4]().

@basawyer – any luck on your end with a patch? I just started on a dual-pointer recursive approach that may do the trick. It's slated on the [v4] channel, but as it's a bug in nature, it will also be applied to v3 as well.

**Comment by nopace** [comment]
Thanks again

**Comment by clarketm** [comment]
@basawyer & @nopace – these `rowspan`/`colspan` edge cases should now be fixed as of [`v5.0.0-rc.1`](https://github.com/clarketm/TableExport/releases/tag/v5.0.0-rc.1). 

If this is not the case, can you please send me a sample `html` structure where the algorithm fails?

> NOTE: **v5.0.0-rc.x** will remain a *release candidate (rc)* until this `rowspan`/`colspan` bug is resolved. At which time it will be published as a *stable* release.

**Comment by wo00421309** [comment]
[Untitled1.txt](https://github.com/clarketm/TableExport/files/1043802/Untitled1.txt)
please help me!

**Comment by clarketm** [comment]
@wo00421309 – thanks for the `html` snippet. Let me take a look and I'll see what the problem is.

**Comment by wo00421309** [comment]
can i merge the cell as the question nopace mentioned

**Comment by clarketm** [comment]
@wo00421309 – cell merging is the next feature I'd like to introduce. In this case it looks like the `rowspan` ordering needs to be tracked correctly so the shift you are experiencing doesn't occur. Once this is fixed, I will have a much, much easier time adding cell merge functionality from [SheetJS](https://github.com/SheetJS/js-xlsx#worksheet-object).

**Comment by clarketm** [comment]
@wo00421309 – [`v5.0.0-rc.3`](https://github.com/clarketm/TableExport/releases/tag/v5.0.0-rc.3) applies the appropriate fixes to resolve the aforementioned `rowspan`/`colspan` issues such as the one you highlighted. As far as *cell merge* functionality goes, assuming that there aren't any lingering bugs with either `rowspan` or `colspan`, this is a logic next step as far as enhancements. I created an issue specifically for this feature #69.

**Comment by clarketm** [comment]
Multiple consecutive `colspan` is still broken. Thanks to @dulguun00 for pointing this out. Expect this to be fixed soon.

**Comment by clarketm** [comment]
[`v5.0.0-rc.6`](https://github.com/clarketm/TableExport/releases/tag/v5.0.0-rc.6) introduces dramatic improvements to this `rowspan` / `colspan` bug, effectively resolving it for *most* table constructs. There are a few exceptions, due to the complexity of the native `html` table parsing process, such as when the `colspan` or `rowspan` values introduce noncongruence with the *row* (`<tr>`) or *column* (`<td>` or `<th`>) length (**e.g.** nonsymetric tables).

**Comment by CrestApps** [comment]
I am using v4.0.11 and I am seeing this issue as well. Is there a workaround or a fix for this bug?

**Comment by HarrySystems** [comment]
I've tested it with v5.0.0-rc.6 and I'm still facing this problem (as you can see in this [pen](https://codepen.io/harrysystems/pen/ZJRKOd))

**Comment by vishalakula19** [comment]
I am using v5.2.0 when there are 2 rowspans consecutively it ignores the 2nd one.  Please help!!


[table-rowspan.txt](https://github.com/clarketm/TableExport/files/2974945/table-rowspan.txt)
![table-snap](https://user-images.githubusercontent.com/20358277/54487715-36fcc780-48bf-11e9-88d0-725fb90b2903.jpg)
![table-excel-snap](https://user-images.githubusercontent.com/20358277/54487718-3f550280-48bf-11e9-9393-7accd6e46d1c.jpg)

**Comment by onlymaj** [comment]
Also this structure of html does not work for me too . I tested with version 5.2.0
<img width="742" alt="Screen Shot 1398-05-16 at 23 00 56" src="https://user-images.githubusercontent.com/3592938/62648177-7d82b980-b967-11e9-8c8d-f28be897cab6.png">
